### ISSUE TITLE
Do not allow modify url while it’s loading 

### ISSUE THREAD

**Issue by Ronvaisman** [andrefmsilva/iplaytvaio-bugs#10]
**Describe the bug**
While the url is loading for the first time (new EPG or new channels) while the loading screen appears it is possible the remove the url or modify it

**To Reproduce**
1. Go to Settings
2. Click on Guide sources 
3. Click on via remote URL
4. Add this url: https://guidexl.tv4.live/
5. While it’s loading the url you can still modify it

**iOS version**: 
iPhone 12 Pro
OS: 14.7
Iptv: 1.0

**Expected behavior**
Block keyboard / editing while it’s loading
![68D116C3-3C83-4410-B9AA-BD86B056DB88](https://user-images.githubusercontent.com/575917/120995513-21b92f80-c78e-11eb-800e-bd3548edf280.png)

**Comment by andrefmsilva** [comment]
Fixed in next build
