### ISSUE TITLE
Filter / Search movies and TV-Shows

### ISSUE THREAD

**Issue by kkollsga** [andrefmsilva/iplaytvaio-bugs#128]
**Describe the feature**
iPlayTV on iPhone, and especially on Apple TV has a beautiful layout and look, but is lacking even the most basic search and filter features. Could you add search and filters to the app? Especially for VOD sections? The data is already in the app when you choose a movie, so it should be relatively easy to utilize that data for searches ech.

I would like the ability to: 
- search for specific movies/tv-shows
- To re-order the movie/tv-shows list to; alphabetic, by rating, by popularity, by release data etc
- To filter movies/tv-shows; By genre, by tags, by language, by director, by starring etc
- Recommendations based certain criteria (like plex)

BTW it would be nice to be able to search the TV-guide as well. Perhaps with some recommendations also?

**Additional context**
Navigating VOD folders is a nightmare. For instance I want to watch 8 Mile in a folder containing more than 1000 movies. How do I do that? Impossible, the order of the movies are random, there is no search or filter functions. Even when I know the movie exist I just have to give up.

The Plex app solves this issue quite nicely with multiple sort, filter and search features.
See below for some inspirations from this awesome app.
![Plex interface](https://techcrunch.com/wp-content/uploads/2019/08/plex-desktop-movies-1024x659.jpg?w=1390&crop=1)

![Plex order](https://nascompares.com/wp-content/uploads/2019/08/plex-user-interface.jpeg)

![Plex categories](https://external-preview.redd.it/cxkEdhzhnKgb-742Z-hgjnl-qTRHnfVce9XFz0E0RFU.jpg?auto=webp&s=92b5c3e11b9873a714b56f110d889b42da7228e7)

**Comment by MNLFDF** [comment]
When you go to “Movies” at the iPhone/iPad app, you get a search option at the left top of the screen. And when you are within “Movies” (or TV Channels/TV Series) at the AppleTV app, you simply double press on the “Play/Pause” button to get the search options. These are searching through the complete playlist. Isn’t that what you want?

**Comment by kkollsga** [comment]
Thanks, I didn't realize there was this function =)
