### ISSUE TITLE
Scrolling in channels groups - no auto update

### ISSUE THREAD

**Issue by lindblomstefan** [andrefmsilva/iplaytvaio-bugs#139]
**Describe the bug**
It might not be the intention but when in menu option Channels, all the groups show. While scrolling up/down they have previously (current atv app) auto updated channels "on hover"

**To Reproduce**
1. Go to Channels
2. Scroll in list

**iOS version**: 16.3.1
**iPlayTV AIO version**: v1.1.0 (20230314.0)
**iOS device**: iPhone 11
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
The channels section to the right to auto update as scrolling through the channel groups

**Comment by lindblomstefan** [comment]
As said, this might be exactly how it's intended to behave.

**Comment by andrefmsilva** [comment]
Yes, it was designed to behave like that. 
Now we have a button on top to reconfigure the screen and it feels strange to change the screen content if you only want to hide/protect some other group or change screen config.

**Comment by lindblomstefan** [comment]
Makes sense! I'm probably in old behaviors and need to learn new tricks :) 

Please close this one if appropriate.
