### ISSUE TITLE
EPG not loading at all

### ISSUE THREAD

**Issue by AlRam79** [andrefmsilva/iplaytvaio-bugs#141]
EPG stopped working all of a sudden, has been working just fine for 6-7 months or so.

Tried refreshing, adding EPG path manually, re-adding account and reinstalling app to no avail. 

TvOS/ATV 4k gen 2.
Same account on iOS works just fine.

**Comment by ralfschramm** [comment]
same here :(

**Comment by AlRam79** [comment]
Actually, the EPG got back two days ago, all of a sudden. Don’t know of there was a version update or so. I haven’t done anything…/Alen14 apr. 2023 kl. 18:55 skrev Ralf Schramm ***@***.***>:﻿
same here :(

**Comment by andrefmsilva** [comment]
probably some outdated EPG information or some provider problem

**Comment by ralfschramm** [comment]
> probably some outdated EPG information or some provider problem

Hi @andrefmsilva,

the problem still resists :(

See: https://github.com/andrefmsilva/iplaytvaio-bugs/issues/143

Best Regards
Ralf
