### ISSUE TITLE
Sign in with Apple ID on first use

### ISSUE THREAD

**Issue by Jokanaan78** [andrefmsilva/iplaytvaio-bugs#17]
**Describe the bug**

When opening the app for the very first time I'm granted with a pop-up window asking to "Sign in with Apple ID". It's probably trying to check whether there is a PRO signature already or not, but it should only be checked when actually trying to access a PRO feature or when accessing the Settings/PRO menu.

I don't know why I am being asked about my Apple SignIn without even being able to explore the app before.

If I select cancel, then every now and then it comes back again.

**To Reproduce**
1. Open the app for the very first time

**iOS version**: iOS 14.6 and iPadOS 14.6

**iPlayTV AIO version**: Version of iPlayTV this bug occurred on (can be found in Settings tab)
**iOS device**: IPhone XS / iPAD Air2
**Jailbroken**: no
**Reproducible:** Can you reproduce it every time? Yes

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by andrefmsilva** [comment]
Some reference for help: https://stackoverflow.com/questions/51820800/receipt-validation-before-showing-iap-page
