### ISSUE TITLE
Add entire groups to favorites

### ISSUE THREAD

**Issue by Jokanaan78** [andrefmsilva/iplaytvaio-bugs#19]
**Describe the feature**
There should be an option to add an entire group of channels to favorites, instead of having to select one by one

Could also be done by allowing a "select all channels from this group" when in selection mode

**Comment by andrefmsilva** [comment]
It is already possible:

https://user-images.githubusercontent.com/1292362/125347313-afbaa400-e352-11eb-96a0-3dcdd9b122bd.mp4

**Comment by Jokanaan78** [comment]
I've seen it, but the steps to select all items under a specific group are awkward: there's no options when you select a group, so to enter selection mode you have to select 1 item, then unselect it and then select all becomes effective... shouldn't there be a pop up menu at the level of groups (to add to favorites, hide, select, etc)?

 https://user-images.githubusercontent.com/85512877/125613077-beca729e-b2f7-4004-a7f0-10766debc43a.MOV

**Comment by andrefmsilva** [comment]
On it!!
