### ISSUE TITLE
No Catchup / Replay for channels

### ISSUE THREAD

**Issue by GilbertMeister** [andrefmsilva/iplaytvaio-bugs#25]
No catchup / replay information is displayed in the live channels. Even if a subscription has been completed.

**Comment by andrefmsilva** [comment]
Can you re test in the latest build? i did some fixes for this...

**Comment by GilbertMeister** [comment]
Hi André

Thank you for your great work. 

The catchup / replay works now. But when I watch in replay I can‘t forward to another place in the replay. 

Regards, Gilbert

Am 07.07.2021 um 10:06 schrieb André Silva ***@***.***>:

﻿
Can you re test in the latest build? i did some fixes for this...
