### ISSUE TITLE
EPG Guide Filters: add favorites 

### ISSUE THREAD

**Issue by GilbertMeister** [andrefmsilva/iplaytvaio-bugs#37]
In the EPG Guide Filter view: add favorites channels categorie

**Describe the feature**
A clear and concise description of what the feature is.

**Additional context**
Add any other context about the feature here. You can add for example screenshots of other app or designs.

**Comment by andrefmsilva** [comment]
The app already has that option.

![Image](https://user-images.githubusercontent.com/1292362/190930205-7cb1f46b-df9e-42a2-9b22-f085e1c490c9.jpeg)

**Comment by csholmq** [comment]
@andrefmsilva If I may add. I am missing the option to select a single favorites list. When I click All favorites it is presented all jumbled between my 4 favorite lists and there is no way to reorder in that view (from what Ive seen).

**Comment by csholmq** [comment]
https://github.com/andrefmsilva/iplaytvaio-bugs/issues/71 is related to the order of it but I am referring to the ability of looking at the EPG for just the channels in a specific favorite list.
