### ISSUE TITLE
Can't switch icon

### ISSUE THREAD

**Issue by Yohannn22** [andrefmsilva/iplaytvaio-bugs#38]
**Describe the bug**
I can't change from dark to light icon.
Changing from menu is OK, but can't see the change on my springboard.

**To Reproduce**
1. Go to 'general'
2. Click on '.icon.'
3. Scroll down to '.light.'

**iOS version**: iOS15
**iPlayTV AIO version**:20210706.0
**iOS device**: iPhone 12 Pro
**Jailbroken**: No
**Reproducible:** yes

**Comment by Yohannn22** [comment]
https://user-images.githubusercontent.com/87023380/124611769-0bc48a80-de72-11eb-97ca-d4c83168a40f.MP4

**Comment by andrefmsilva** [comment]
Maybe some iOS 15 bug, lets wait for the final release...i did a quick test and it was working in iOS simulator

**Comment by Yohannn22** [comment]
Issue fixed now with beta 3 of iOS 15
