### ISSUE TITLE
Doesnt show movie

### ISSUE THREAD

**Issue by yakuuu77** [andrefmsilva/iplaytvaio-bugs#39]
Hello when we group by alphabetically or added date thats look like my screenshot
![602ACF69-03A0-459E-8045-89133A46F247](https://user-images.githubusercontent.com/87077622/124766482-40e6e080-df37-11eb-942c-a60368ee03b2.png)
![8F6AB759-C41E-4156-91AB-78A98FF99F87](https://user-images.githubusercontent.com/87077622/124766489-42180d80-df37-11eb-8f8f-616c381be319.png)

**Comment by andrefmsilva** [comment]
Those are expandable sections. You need to click on one of those items to open/close it

**Comment by yakuuu77** [comment]
My bad sorry thats was sort by to use
