### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by yakuuu77** [andrefmsilva/iplaytvaio-bugs#43]
I sent you a private message on discord but I think you haven't seen it, My problem is that when I subscribe to iplaytv pro, EPG movies bug but when I do not subscribe everything works perfectly I send you screenshot here
![image_123986672_1](https://user-images.githubusercontent.com/87077622/124966785-fbeca800-e023-11eb-8f2a-35b4d7f16fd2.JPG)
![image_123986672_2](https://user-images.githubusercontent.com/87077622/124966790-fdb66b80-e023-11eb-8956-fb268e463bd2.JPG)

**Comment by andrefmsilva** [comment]
Fixed in latest build.
