### ISSUE TITLE
PiP - not working outside of app..

### ISSUE THREAD

**Issue by BledItIt** [andrefmsilva/iplaytvaio-bugs#45]
PiP will not work outside of the app.

Start PiP and then when moving outside of app it closes down.

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
iOS version : 14.6

**iPlayTV AIO version**: Version of iPlayTV this bug occurred on (can be found in Settings tab)
iPlay TV Version - v1.0(20210706.0)

**iOS device**: For example iPhone XS, iPad mini, etc.
iPhone 11 Pro

**Jailbroken**: Whether or not your device is jailbroken
No

**Reproducible:** Can you reproduce it every time? Or is it random?
Yes - it happens no matter what

**Expected behavior**
I would think that if I went to browser or email (for example) I would still have PiP for iPlay TV to remain. 

**Screenshots**
Tough - as when you exit the app the PiP is gone.

**Video**
If Needed I will upload..

**Additional context**

**Comment by andrefmsilva** [comment]
For now PIP only works inside the app.
I'll add support for native PIP if i find some way to make it work with custom players that use ffmpeg.
