### ISSUE TITLE
Update/refresh playlist

### ISSUE THREAD

**Issue by Cliffer22** [andrefmsilva/iplaytvaio-bugs#52]
Got a problem when trying to update/refresh my playlist. The app take me off my Wi-Fi and I get this error message. When I go back to watch live tv it brings me back on my Wi-Fi and there is no problem with my connection, but it will not update the playlist?

![5268C442-7F7B-4BD1-836F-D207D141A831](https://user-images.githubusercontent.com/87077802/129209898-549637cb-f933-4415-b1d1-8f1bebd7471c.png)

**Comment by andrefmsilva** [comment]
I've check and the app is not doing anything special that can disconnect from network. Also the app can't force iOS to disconnect from any network.
