### ISSUE TITLE
Hiding groups/channels needs too much clicks

### ISSUE THREAD

**Issue by MNLFDF** [andrefmsilva/iplaytvaio-bugs#66]
My IPTV subscription gives me lots of Tv Channels, Movies and TV Shows fro many countries. So I want (need) to hide a lot of those countries (groups in the library). Now you need to select a group, then select the upper right corner for edit mode, then press the left upper corner to select all, then select the bottom right corner to get a menu where you need to press “hide”. Can’t you get us a screen in the setup “manage content” and give us a AppleTV like screen which we can select and unselect things very easy? Also to get things to “favorites” and “Parent control”.

Preferred screen:
![498959F7-40D8-4883-A908-9683B8C10133](https://user-images.githubusercontent.com/71567372/148687972-83cc26ac-329e-4a64-ad20-5a8a2a52980a.jpeg)

**Comment by andrefmsilva** [comment]
I've added a new screen in settings to manage playlist content...
