### ISSUE TITLE
Keep hiding Countries which are hided by user

### ISSUE THREAD

**Issue by MNLFDF** [andrefmsilva/iplaytvaio-bugs#67]
(Also a problem with the AppleTV app).

When I hided several countries from my IPTV subscription (TV channels, Movies, TV Series), those countries pop-up again when the IPTV seller added new channels to those countries.  As a result I need to check the complete list again and hide all non wanted countries again. And this happens frequently! Isn’t it possible when a user hide a country, it keeps blocked from showing in the library? You can maybe think of a (user configurable) way to show new items  at “NEW” so users can decide to add them even if preferred.

I need to hide a lot of counties tv channels again, and again, and again when there are new updates.
![E428213D-C7BA-4DB3-B2BE-C0DBB98DA76A](https://user-images.githubusercontent.com/71567372/148689188-6902863e-3bec-43b5-aed4-ea8ba29ef0ea.png)

**Comment by andrefmsilva** [comment]
when you hide a category in the new manage screen it will automatically hide all new items added to that category. 
Please do some tests and let me know if it works
