### ISSUE TITLE
[Improvement] Adding keyboard Passwords integration

### ISSUE THREAD

**Issue by meyerf99** [andrefmsilva/iplaytvaio-bugs#7]
**Describe the improvement**
Adding keyboard "Passwords" integration for iCloud login.

**To Reproduce**
1. Start App
2. Asking for Sign in with Apple ID
3. Keyboard open and "Passwords" missing

**iOS version**: iOS 14.6
**iPlayTV AIO version**: 1.0
**iOS device**: iPhone 11
**Jailbroken**: Not
**Reproducible**: Reproducible every app startup

**Expected behavior**:
Adding integration of "Passwords" in keyboard

**Screenshots**:
![31DA85F6-4D23-447A-9418-F70D8C832725](https://user-images.githubusercontent.com/28959963/120938512-563bd580-c713-11eb-99d8-c61d029e797b.jpeg)

![F0040F55-5B52-4360-A6CF-5B9E50F3C2C4](https://user-images.githubusercontent.com/28959963/120938514-589e2f80-c713-11eb-9162-742d7d9c3de7.jpeg)

**Comment by andrefmsilva** [comment]
This is something that i can't do. 
In order to validate if the user has a valid PRO subscription i need to check the purchase receipt and sometimes to retrieve it the system needs to login again into your iCloud account...this login alert is managed by iOS and i don't have control over it.

**Comment by andrefmsilva** [comment]
Reopened to implement a different flow that avoids this popup

**Comment by andrefmsilva** [comment]
Reopened to implement a different flow that avoids this popup

**Comment by andrefmsilva** [comment]
Close because the improvement will be done in #17
