### ISSUE TITLE
Refresh only Favourites channels/ refresh only EPG

### ISSUE THREAD

**Issue by PeroPenx** [andrefmsilva/iplaytvaio-bugs#74]
**Describe the feature**
Faster way of playlist refreshing

1. by doing it just for channels selected in favourites (even if they are from different playlists)
2. refreshing only EPG not playlist and EPG

**Additional context**
Add any other context about the feature here. You can add for example screenshots of other app or designs.

**Comment by andrefmsilva** [comment]
It can't be done. The app needs to download all EPG data because it's not possible to download only information for some channels
