### ISSUE TITLE
Is development still going on?

### ISSUE THREAD

**Issue by MNLFDF** [andrefmsilva/iplaytvaio-bugs#77]
Lots of feedback from people using the iPlusTV app for iOS through TestFlight app, but we don't see any (frequent) updates from the developer. Is development still going on? What is the ETA for the final release of this app in the AppStore?

I really like the iPlayTV apps (tvOS and now iOS/iPadOS), but i don't see any reported error fixes or -feedbacks back in the current iOS/iPadOS development. Can you please tell us what the next steps are? When can we expect a new test build?

**Comment by andrefmsilva** [comment]
Yes, i'm working on it every day.
Right now i'm working on iCloud stuff (complete new logic) and stalker support.

Both are almost done, and i'm fixing small stuff and improve them for the release

https://github.com/andrefmsilva/iplaytvaio-bugs/projects/3
