### ISSUE TITLE
Friendly Request | iOS & iPadOS Version

### ISSUE THREAD

**Issue by mucke5** [andrefmsilva/iplaytvaio-bugs#78]
Hi. I am a big fan of your tvOS version. Unfortunately I don't have an active TestFlight for iOS or iPadOS. Do you still offer one for new users?

**Comment by mucke5** [comment]
@andrefmsilva any chances to get an invitation?
I can also provide a mail if needed.

**Comment by mucke5** [comment]
https://t.me/TestFlightX/2604

@andrefmsilva maybe you can kick some inactive users to open some seats?

**Comment by andrefmsilva** [comment]
more slots added
