### ISSUE TITLE
Automatic Renaming

### ISSUE THREAD

**Issue by mfigaro** [andrefmsilva/iplaytvaio-bugs#79]
**Describe the feature**
There are channel incorrect names that can be automatically cleaned. 

**Additional context**
Some known and common channel wrong naming can be automatically fixed with its correct typing. Example: s k y news can automatically renamed in Sky News. 
Possible?

**Comment by andrefmsilva** [comment]
unfortunately adding that kind of rules can cause problems for other name formats
