### ISSUE TITLE
New group selection/hiding

### ISSUE THREAD

**Issue by MNLFDF** [andrefmsilva/iplaytvaio-bugs#82]
I like the way how separate channels can be hided in the newest Beta (27-5). It’s going much quicker and easier than before. Why not the same approach for the Groups?

 I really need to hide over 100 groups (and most of the time also when the IPTV list is renewing I have to hide lots of them again and again). The most easiest way would be to select all groups (or get a option like at the separate channels) and deselect (or select) the one you want to be left and then press the hide option. Now I need to press and hold every group (like I said over 100) one by one to hide them. 

But like I said it’s way better then before.

P.S. At first when I used the new hiding method, I thought nothing happened, but my subscriptions were been updating in the background 😆

**Comment by andrefmsilva** [comment]
New Manage screen added in settings will help in this case.
