### ISSUE TITLE
Separate IPTV subscriptions showing separately 

### ISSUE THREAD

**Issue by MNLFDF** [andrefmsilva/iplaytvaio-bugs#83]
At this moment I have 3 IPTV subscriptions added to this app. They are all showed at the same Channel List. Because these subscriptions are also used on other devices and can only handle one user at the time. So it would be easier if the user can select the IPTV Subscription which he/she want to use (like it’s been done at this app on our AppleTVs).

**Comment by andrefmsilva** [comment]
The app was designed to merge all the subscriptions into one but you can still filter the channels, movies and shows to show only one subscription. 

Just go to the filters screen and you should have an option there to choose the subscription that you want to see. Those configurations are saved across app launches so you don't need to do them every time you open the app again.

In my opinion this is the best way to handle multiple subscription and i don't have plans to change how it was done in this new version.
