### ISSUE TITLE
Long Press Goups menu change half way the screen (mirror)

### ISSUE THREAD

**Issue by MNLFDF** [andrefmsilva/iplaytvaio-bugs#84]
Long press on a Group gives you a menu. This menu changes (it mirror’s) when you long press on Groups on the lower half of the screen. (See screen shots). 

![7537CD39-BB77-41C2-8692-EE2ECB725E69](https://user-images.githubusercontent.com/71567372/170738791-e36be955-ab96-4330-a336-480aa200cc5d.jpeg)

![8178C0D1-8A61-4381-A0A0-929706C4AAE1](https://user-images.githubusercontent.com/71567372/170738796-b6f2d0f2-19a1-4ffa-aa6b-1034f2432caf.jpeg)

**Comment by andrefmsilva** [comment]
That is handled by iOS...the system decides the best way to show the menu and i can't change it.
