### ISSUE TITLE
Tap hold on channel takes a few sec to open the menu

### ISSUE THREAD

**Issue by Ronvaisman** [andrefmsilva/iplaytvaio-bugs#9]
**Describe the bug**
Device: iPhone 12 Pro
When I tap and hold on a channel to bring up the menu, the menu doesn’t show up immediately it takes 1+ sec

**To Reproduce**
1. Go to channel
2. Tap and hold on channel
3. Menu will open after 1+ sec

**Comment by andrefmsilva** [comment]
That menu is managed by apple and i can't change the time it takes to open.
